Add `qml.capture.eval_jaxpr` for improved execution of dynamic array creation (#7052)
**Context:**

```
def f(i):
    return jax.numpy.arange(i)

jaxpr = jax.make_jaxpr(f)(3)
jax.core.eval_jaxpr(jaxpr.jaxpr, jaxpr.consts, 2)
```
```
XlaRuntimeError: UNKNOWN: ....  error: 'mhlo.dynamic_iota' op can't be translated to XLA HLO
```

To bypass this issue, I'm adding in a `qml.capture.eval` function that
basically matches the behavior of `jax.core.eval_jaxpr`, but is capable
of handling the creation of dynamic arrays.

We then always use it to execute jaxpr, so that we can always have
dynamic array creation.

**Description of the Change:**

Adds `qml.capture.eval_jaxpr`. Switches all use of `jax.core.eval_jaxpr`
to `qml.capture.eval_jaxpr`.

Also adds a `qml.capture.base_interpreter.FlattenedInterpreter`. We use
this for any "evaluation style" interpreters to inherit the flattened
registrations for control flow primitives.

**Benefits:**

We can create dynamic arrays.

**Possible Drawbacks:**

**Related GitHub Issues:**

[sc-85970]

---------

Co-authored-by: Pietropaolo Frisoni <pietropaolo.frisoni@xanadu.ai>
Co-authored-by: Andrija Paurevic <46359773+andrijapau@users.noreply.github.com>