A unified `split_non_commuting` transform for any tape (#5729)
**Context:**

Right now `qml.Device` choose between applying `hamiltonian_expand`,
`sum_expand`, and `split_non_commuting` based on the contents of the
measurements and selectively applies them. Under the new device API, we
cannot simply stick these three transforms into the transform program,
as they currently raise errors when applied to ordinary circuits.

```
>>> tape = qml.tape.QuantumScript([], [qml.probs(wires=(0,1))])
>>> qml.transforms.hamiltonian_expand(tape)
ValueError: Passed tape must end in `qml.expval(H)`, where H is of type `qml.Hamiltonian`
>>> qml.transforms.split_non_commuting(tape)
NotImplementedError: When non-commuting observables are used, only `qml.expval` and `qml.var` are supported.
>>> qml.transforms.sum_expand(tape)
([<QuantumScript: wires=[0, 1], params=0>],
 <function pennylane.transforms.hamiltonian_expand.sum_expand.<locals>.processing_fn(expanded_results)>)
```

While `sum_expand` has sensible default behaviour that will not raise
errors on standard functions, it is not as efficient for large
hamiltonians and commuting measurements. We therefore need a new
transform that selectively applies each of the above transforms based on
the contents of the circuit. This transform is necessary for the
development of devices that do not natively support hamiltonians or
non-commuting measurements.

**Description of the Change:**

- `split_non_commuting` now incorporates the capabilities of
`sum_expand` and `hamiltonian_expand`
- Tests from `test_hamiltonian_expand.py` are copied to
`test_split_non_commuting.py`
- `grouping_strategy` keyword argument added to `split_non_commuting` to
allow users to choose between grouping based on overlapping wires
(`"wires"`), or using the graph colouring algorithm (`"qwc"`)
implemented in `pauli.group_observables`.

**Follow-up TODOs**

- Clean up `Device.batch_transform` to use the new `split_non_commuting`
- Option to add diagonalizing gates to each tape
- A transforms transform `shots_only` to wrap around
`split_non_commuting`

**Related GitHub Issues:**
[sc-50536]
[sc-59046]

---------

Co-authored-by: Ahmed Darwish <exclass9.24@gmail.com>
Co-authored-by: Thomas R. Bromley <49409390+trbromley@users.noreply.github.com>