fix: privatize `num_wires` on `AbstractWires` class (#10032)
**Context:**

Because `num_wires` is available as a property, downstream consumers
might use it for various calculations. That's fine and all until you
consider objects like `Wire[-1]` which have unbounded length. If the
user doesn't guard with `shape_fixed` then you might have
`num_wires=-1`  poisoning your calculation.

**Description of the Change:**

Let's make num_wires a private attribute _num_wires and this property
can only be accessed through len,
```pycon
>>> aw = Wire[5]
>>> len(aw)
5
>>> aw.shape_fixed
True
>>> aw = Wire[-1]
>>> len(aw)
TypeError: len() is undefined for AbstractWires(-1) with unknown number of wires.
>>> aw.shape_fixed
False
```

**Benefits:** No ambiguity

**Possible Drawbacks:** None identified.

[sc-128271]