Fix custom_staging_rule to not always return dynamically shaped arrays (#8004)
**Context:**

In testing some changes to catalyst, I realized that the capture
primitives were returning `DShapedArray` even when the corresponding
variable didn't actually have a dynamic shape.

For the code:
```
qml.capture.enable()
jax.config.update("jax_dynamic_shapes", True)

def circuit(x):
    if x > 2.7:
        res = x * 4
    elif x > 1.4:
        res = x * 3
    else:
        res = x

    return res

jax.make_jaxpr(qml.capture.run_autograph(circuit))(jnp.array(4))
```
I was getting:
```
File [~/Prog/pennylane/pennylane/ops/op_math/condition.py:720](http://localhost:8889/~/Prog/pennylane/pennylane/ops/op_math/condition.py#line=719), in _validate_abstract_values(outvals, expected_outvals, branch_type, branch_index)
    717 if jax.config.jax_dynamic_shapes:
    718     # we need to be a bit more manual with the comparison.
    719     if type(outval) != type(expected_outval):  # pylint: disable=unidiomatic-typecheck
--> 720         _aval_mismatch_error(branch_type, branch_index, i, outval, expected_outval)
    721     if getattr(outval, "dtype", None) != getattr(expected_outval, "dtype", None):
    722         _aval_mismatch_error(branch_type, branch_index, i, outval, expected_outval)

File [~/Prog/pennylane/pennylane/ops/op_math/condition.py:693](http://localhost:8889/~/Prog/pennylane/pennylane/ops/op_math/condition.py#line=692), in _aval_mismatch_error(branch_type, branch_index, i, outval, expected_outval)
    692 def _aval_mismatch_error(branch_type, branch_index, i, outval, expected_outval):
--> 693     raise ValueError(
    694         f"Mismatch in output abstract values in {branch_type} branch "
    695         f"#{branch_index} at position {i}: "
    696         f"{outval} vs {expected_outval}."
    697     )

ValueError: Mismatch in output abstract values in false branch #0 at position 0: i32[] vs ~int32[].
```
Because the output of `qml.cond` was getting promoted to being a
dynamically shaped array.

**Description of the Change:**

Use `jax.core.ShapedArray` if the output has no abstract dimensions.

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

[sc-96906]

---------

Co-authored-by: Mudit Pandey <18223836+mudit2812@users.noreply.github.com>