Fix `LocalHilbertSchmidt` template (#4719)
[sc-48521]


When run with a `QNode`, the `LocalHilbertSchmidt` template raises:
```
RuntimeError: No queuing context available to append operation to.
```

The decomposition uses `qml.apply` without checking that something is
recording. This failure was not found because there were no integration
tests checking that the template worked in a `QNode`.