[Capture] Add execution support for `broadcast_in_dim_p` and `iota_p` (#6865)
**Context:**

While we can capture the creation of arrays with a dynamic shape like
`jnp.ones`, `jnp.zeros`, and `jnp.arange`, jax does not support
executing these equations:
```
def f(n):
    return jax.numpy.ones((n,))

jaxpr = jax.make_jaxpr(f)(2)
jax.core.eval_jaxpr(jaxpr.jaxpr, jaxpr.consts, 4)
```
```
...
XlaRuntimeError: UNKNOWN: [/var/folders/k1/0v_kvphn55lgf_45kntf1hqm0000gq/T/ipykernel_16612/1590642475.py:2:11](http://localhost:8888/var/folders/k1/0v_kvphn55lgf_45kntf1hqm0000gq/T/ipykernel_16612/1590642475.py#line=1): error: 'mhlo.dynamic_broadcast_in_dim' op can't be translated to XLA HLO
...
```

I think `jax.core.eval_jaxpr` is trying to jit and lower the
`broadcast_in_dim` primitive, but can't. This problem propogates to
executing any jaxpr with a `PlxprInterpreter`

**Description of the Change:**

Registers special handling for `broadcast_in_dim` and `iota`.

**Benefits:**

We can execute the creation of dynamically shaped arrays.

**Possible Drawbacks:**

Sensitive to the location of `jax.lax.broadcast_in_dim_p` and
`jax.lax.iota_p`. So this may break if jax moves things around.

**Related GitHub Issues:**

[sc-82653] [sc-82656]

---------

Co-authored-by: lillian542 <38584660+lillian542@users.noreply.github.com>
Co-authored-by: Mudit Pandey <mudit.pandey@xanadu.ai>
Co-authored-by: Pietropaolo Frisoni <pietropaolo.frisoni@xanadu.ai>