Patch for equality check of Adjoint2 with Adjoint (#9702)
**Context:**

```
>>> qp.assert_equal(qp.adjoint(Op2()), qp.adjoint(qp.H(0)))
AssertionError: op1 and op2 are of different types.  Got <class 'pennylane.ops.op_math.adjoint2.Adjoint2'> and <class 'pennylane.ops.op_math.adjoint.AdjointOperation'>.
```

**Description of the Change:**

Making it so that `Adjoint2` is comparable to `Adjoint`

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

---------

Co-authored-by: Christina Lee <christina@xanadu.ai>