trotter_error: acc exp values not states
Replaces `new_state` with `order_sum = 0j` and accumulates the result of
`state.dot(new_state)` instead.

This should be mathematically equivalent with the previous behaviour and
saves on resource use since we're adding numbers instead of
quantum state vectors.

gh issue: #8152