Defer calculating classical cotransform and argnums till needed (#6716)
**Context:**

Currently, we do preprocessing and transform program setup in the qnode.
We have to do this, because we have to cache the classical cotransforms
and argnums in the qnode layer. If we tried to setup the full transform
program later, we wouldn't have access to the classical cotransform
information anymore.

But by caching the qnode, args, and kwargs instead of calculated
cotransform information, we can further add to and modify the transform
program after we have moved on from the qnode level. This allows us to
setup the workflow inside of `qml.execute`. Now we only use the
qnode-like kwargs from `qml.execute`. We don't use the "developer like"
kwargs like `inner_transform_program` and `config`. We will no longer
need two "modes" for qml.execute, where one mimics the qnode and one is
more developer focused. We can strictly mirror the interface of the
QNode in `qml.execute`. This also allows us to run our resolution and
setup in `qml.execute`.

This does also provide some improvements.  Where we previously got:

```
x = jax.numpy.array(0.5)

tape = qml.tape.QuantumScript([qml.RX(x, 0)], [qml.expval(qml.Z(0))], shots=100)
dev = qml.device('lightning.qubit', wires=2)
jax.jacobian(qml.execute)((tape,), device=dev, diff_method="backprop")
```
```
Invoked with: <pennylane_lightning.lightning_qubit_ops.StateVectorC128 object at 0x156749cf0>, [0], False, [Traced<ConcreteArray(0.5, dtype=float32, weak_type=True)>with<JVPTrace(level=2[/0](http://localhost:8888/0))> with
  primal = Array(0.5, dtype=float32, weak_type=True)
  tangent = Traced<ShapedArray(float32[], weak_type=True)>with<JaxprTrace(level=1[/0](http://localhost:8888/0))> with
    pval = (ShapedArray(float32[], weak_type=True), None)
    recipe = LambdaBinding()]
```
We now get:
```
QuantumFunctionError: Device <lightning.qubit device (wires=2) at 0x1275a7ce0> does not support backprop with requested circuit.
```

We can also specify `diff_method="best"` in `qml.execute`.

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

---------

Co-authored-by: Andrija Paurevic <46359773+andrijapau@users.noreply.github.com>
Co-authored-by: andrijapau <andrija.paurevic@xanadu.ai>
Co-authored-by: Mudit Pandey <mudit.pandey@xanadu.ai>