Update `typing_extensions` pinning in `requirements.txt` (#6508)
Required due to datasets issue with python 3.12

> Hey all, there's a few things undergoing checks right now, but I
believe I have found a potential problem with datasets under Python 3.12
---
TypeError: type 'typing.TypeVar' is not an acceptable base type
This is due to the external dep
https://github.com/python/typing_extensions/issues/243
We need to immediately bump the typing_extensions package to 4.6 minimum
to ensure compatibility with 3.12