feat: autograph: add support for logical operations (`and`, `or`, `not`) (#8006)
## Context:

Currently, our `autograph` module does NOT contain support for logical
operations; specifically, `and`, `or` and `not`.

## Description of the Change:

**Source Code**

This PR adds special handling to `ag_primitives.py` so that once the
transformer encounters these logical operations, they are properly
handled. Here's an example,

```python
import pennylane as qml

qml.capture.enable()

@qml.qnode(qml.device("default.qubit", wires=1), autograph=True)
def circuit(param):
    if param >= 0 and param <= 1:
        qml.H(0)
    return qml.state()
```
```
>>> circuit(0.5)
Array([0.70710677+0.j, 0.70710677+0.j], dtype=complex64)
```

Before this change, this would have errored out with,
```
CaptureError: Autograph must be used when Python control flow is dependent on a dynamic variable (a function input). Please ensure that autograph=True or use native control flow functions like for_loop, while_loop, etc.
```

**Testing Strategy**

Each logical operation get its own test class. There I wrote some unit
tests as well as integration tests with the qnode, for loop and while
loop.

## Benefits:

Allows for more expressive functions to be written.

## Possible Drawbacks: 

None identified.

[sc-76119]

---------

Co-authored-by: Pietropaolo Frisoni <pietropaolo.frisoni@xanadu.ai>