[new opmath 4] Update tests to pass under new opmath (#5335)
Update tests to pass under new opmath using a context manager and
fixture

Branching: https://github.com/PennyLaneAI/pennylane/pull/5269 >
https://github.com/PennyLaneAI/pennylane/pull/5216 >
https://github.com/PennyLaneAI/pennylane/pull/5322 >
https://github.com/PennyLaneAI/pennylane/pull/5335

- [x] Update Hamiltonian tests
- [x] remove all occurences of enable/disable_new_opmath (currently
still missing: in qchem and group_observables)
- [x] `tests/ops/op_math` pass *see caveat below in `test_exp.py`
- [x] `tests/ops/qubit/` pass (includes hamiltonian tests)
- [x] `tests/ops/` pass *except some blockers in
tests/ops/functions/test_assert_valid.py
- [x] `tests/pulse` pass *see pickle blocker, could be local
- [x] `tests/tape/`
- [x] `tests/tape/`
- [x] `tests/resource/`
- [x] `tests/qnn/`
- [x] `tests/qinfo/`
- [x] `tests/numpy/`
- [x] `tests/logging/`
- [x] `tests/kernels/`
- [x] `tests/fermi/`
- [x] `tests/fourier/`
- [x] `tests/math/`

Note that there are currently some tests and parts of the codebase that
enable/disable new opmath, which affects other tests by changing the
global variable `__use_new_opmath`

Blockers:

- [x] `test_exp.py::TestDecomposition::test_generator_decomposition` 
- [x] `tests/ops/functions/test_generator.py` 
- [x] `tests/ops/functions/test_is_commuting.py` require changes in
`qml.is_commuting`
- [x]
`tests/ops/functions/test_assert_valid.py::test_generated_list_of_ops`
- [x]
`tests/ops/functions/test_assert_valid.py::test_explicit_list_of_ops`
- [x] qml.equal handles LinearCombination correctly and tests in
`tests/ops/functions/test_equal.py::TestObservablesComparisons` pass
_also_ for LinearCombination
- [x] >> Update `tests/ops/functions/test_equal.py`
- [x] tests/pulse/test_pytree.py::test_standard_validity `E
AttributeError: Can't pickle local object
'test_standard_validity.<locals>.f1'`

[sc-57841]

---------

Co-authored-by: Mudit Pandey <mudit.pandey@xanadu.ai>
Co-authored-by: lillian542 <38584660+lillian542@users.noreply.github.com>
Co-authored-by: Pietropaolo Frisoni <pietropaolo.frisoni@xanadu.ai>
Co-authored-by: Christina Lee <christina@xanadu.ai>
Co-authored-by: albi3ro <chrissie.c.l@gmail.com>
Co-authored-by: Utkarsh <utkarshazad98@gmail.com>
Co-authored-by: Astral Cai <astral.cai@xanadu.ai>
Co-authored-by: lillian542 <Lillian.frederiksen@xanadu.ai>
Co-authored-by: Alex Preciado <alex.preciado@xanadu.ai>
Co-authored-by: Thomas R. Bromley <49409390+trbromley@users.noreply.github.com>
Co-authored-by: Vincent Michaud-Rioux <vincentm@nanoacademic.com>
Co-authored-by: Josh Izaac <josh146@gmail.com>
Co-authored-by: Nathan Killoran <co9olguy@users.noreply.github.com>
Co-authored-by: Matthew Silverman <matthews@xanadu.ai>
Co-authored-by: Mikhail Andrenkov <mikhail@xanadu.ai>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>