feat: add `MCM_METHOD` & `POSTSELECT_MODE` `StrEnum` objects (#8596)
This PR adds `StrEnum` objects to define specifically what MCM methods /
postselection modes we support. Note that this was added in Python 3.11
which is lower bound now!

⚠️ Custom `mcm_method` strings are no longer allowed with this PR.
Custom device mcm methods must be handled by the device and through the
`mcm_method="device"` input.

Here are some examples for the `mcm_method` kwarg, 
```pycon
>>> import pennylane as qml
>>> from pennylane.devices.execution_config import MCMConfig

>>> # None is allowed
>>> MCMConfig()
MCMConfig(mcm_method=None, postselect_mode=None)

>>> # Supported MCMs get converted to `StrEnum` members
>>> MCMConfig(mcm_method="deferred")
MCMConfig(mcm_method=<MCM_METHOD.DEFERRED: 'deferred'>, postselect_mode=None)
>>> MCMConfig(mcm_method="device")
MCMConfig(mcm_method=<MCM_METHOD.DEVICE: 'device'>, postselect_mode=None)

>>> # Unsupported MCM method gets an error
>>> MCMConfig(mcm_method="random_mcm")
ValueError: 'potato' is not a valid mcm_method. Please use one of the supported mid-circuit measurement methods available: [None, 'deferred', 'one-shot', 'tree-traversal', 'single-branch-statistics', 'device']

```

[sc-86555]

---------

Co-authored-by: Astral Cai <astral.cai@xanadu.ai>