Fix __invert__ dunder method. (#5955)
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
If you've fixed a bug or added code that should be tested, add a test to
the
      test directory!

- [ ] All new functions and code must be clearly commented and
documented.
If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file,
summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.


------------------------------------------------------------------------------------------------------------

**Context:**
```
import pennylane as qml

dev = qml.device("default.qubit")

@qml.qnode(dev)
def circuit(phi, theta):
    qml.RX(phi, wires=0)
    m_0 = qml.measure(wires=0)
    qml.RY(theta, wires=1)
    m_1 = qml.measure(wires=1)
    return qml.sample(~m_0 - 2 * m_1)

circuit(1.23, 4.56, shots=5)
```
yields
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Description of the Change:**
Change the `__invert__` dunder method of `MeasurementValue` so it is
array-compatible, and add tests.

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

---------

Co-authored-by: Mudit Pandey <mudit.pandey@xanadu.ai>
Co-authored-by: Christina Lee <christina@xanadu.ai>