fix: update logic for how `Callable` inputs are validated in `change_op_basis` (#9552)
**Context:**

Previously, we used a greedy `try/except TypeError` block when executing
callable inputs.

This caused `TypeError`s that were being raised deep within the body of
a user's quantum function to be masked in the traceback, lead to
misleading / confusing error messages to the user.

Consider this example, 

```python
import pennylane as qp

def f():
    # Real bug is here!
    wires = "0" + 1
    qp.RZ(0.5, wires=wires)
```
If you try to use `change_op_basis`, you get a completely irrelevant
error,
```pycon
>>> qp.change_op_basis(f, f)
Traceback
...
TypeError: change_op_basis requires that Callable inputs have no parameters. functools.partial can be used to achieve this.
```
If you dig through the traceback you will find the actual error,
```
TypeError: can only concatenate str (not "int") to str
```

**Description of the Change:**

Introduces a new `_validate_callable` helper function that utilizes the
`inspect` module to validate callable inputs. This implements a more
robust approach for detecting whether a provided function contains
unbound mandatory parameters.

**Benefits:**

Code is more robust and testing strategy is improved.

**Possible Drawbacks:**

None identified.

[sc-121194]

---------

Co-authored-by: Yushao Chen (Jerry) <chenys13@outlook.com>