fix OutMultiplier jit issue (#10057)
**Context:**
```
OutMultiplier::_out_multiplier_with_qft
TypeError: Argument '()' ... is not a valid JAX type
```

**Description of the Change:**
Instead of bare ` = ()` assignment, we do `[:0]` to match traceability.

**Benefits:**

**Possible Drawbacks:**
Adder, OutAdder, and Multiplier share similar issue. But not sure if we
should include them as well here.

**Related GitHub Issues:**
[sc-128512]

---------

Co-authored-by: Astral Cai <astral.cai@xanadu.ai>