`run_autograph` is now idempotent (#7001)
**Context:**

When support for control flow with `autograph` (through the `QNode`
execution pipeline) was introduced in
https://github.com/PennyLaneAI/pennylane/pull/6837 a minor bug was
discovered where if you try to apply `autograph` to an already
`autograph`'d function, an _ambiguous_ error would show up,
```python
qml.capture.enable()
from pennylane.capture import run_autograph

dev = qml.device("default.qubit", wires=1)

@qml.qnode(qml.device("default.qubit", wires=1), autograph=True)
def circ(x: float):
    qml.RY(x, wires=0)
    return qml.expval(qml.PauliZ(0))

>>> ag_circ = run_autograph(circ)
>>> ag_ag_circ = run_autograph(ag_circ)
ValueError: closure mismatch, requested ('ag__',), but source function had ()
```

There are a few routes to solve this issue,
1. Raise a more helpful error
2. Throw a warning and proceed with converted function (Catalyst does
this)
3. *Silently* proceed with converted function

**Description of the Change:**

Option (2) was preferred and so if an already converted function is
detected (by the presence of the `ag_uncoverted` attribute), we throw an
`AutoGraphWarning` and just return early. Now we have the behaviour,
```python
qml.capture.enable()
from pennylane.capture import run_autograph

dev = qml.device("default.qubit", wires=1)

@qml.qnode(qml.device("default.qubit", wires=1), autograph=True)
def circ(x: float):
    qml.RY(x, wires=0)
    return qml.expval(qml.PauliZ(0))

ag_circ = run_autograph(circ)
>>> ag_ag_circ = run_autograph(ag_circ)
AutoGraphWarning: AutoGraph will not transform the function <function ...> as it has already been transformed.
>>> ag_ag_circ.func is ag_circ.func
True
>>> ag_ag_circ(-1)
Array(0.5403023, dtype=float32)
```

**Benefits:** Enables `autograph` specific tests to run with the default
`autograph=True` argument through the `QNode`.

**Possible Drawbacks:** 

Suppressed the warnings in the `autograph` test folder. This means that
a future test that emits this warning could be missed if we don't pay
attention to the WAE action that is run weekly.

Fixes [sc-83366]