Fix transform usage in `compile()` docstring example (#5348)
**Context:**

Currently, running the final example in the [`compile()`](https://docs.pennylane.ai/en/stable/code/api/pennylane.compile.html) docstring gives an error:

```
pennylane.transforms.core.transform_dispatcher.TransformError: Decorating a QNode with @transform_fn(**transform_kwargs) has been removed. Please decorate with @functools.partial(transform_fn, **transform_kwargs) instead, or call the transform directly using qnode = transform_fn(qnode, **transform_kwargs). Visit the deprecations page for more details: https://docs.pennylane.ai/en/stable/development/deprecations.html#completed-deprecation-cycles
```

**Description of the Change:**

* Updated the final example in the `compile()` docstring to match the expected usage of `@transform`.

**Benefits:**

* The examples in the `compile()` docstring all run without errors.

**Possible Drawbacks:**

_N/A_

**Related GitHub Issues:**

_N/A_