Replacing `semantic version` with `Version` (#5754)
**Context:** This bug is related to the fact that `semantic_version`
cannot handle a string ending with `.post4`. Without installing a
different `pytorch` version, it can simply be reproduced as follows.

*This is the code snippet to reproduce the error*

```
import semantic_version
string_to_test = '2.1.2.post4'
>>> semantic_version.match(">=1.10.0", string_to_test)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
(....)
ValueError: Invalid version string: '2.1.2.post4'
```
which is fixed by:
```
from packaging.version import Version
string_to_test = '2.1.2.post4'
>>> Version(string_to_test) >= Version("1.10.0")
True
```

**Description of the Change:** We replace `semantic_version` with
`Version`, which can handle such a string.

**Benefits:** The bug does not arise if the user has a `torch`
installation ending with `.post4`

**Possible Drawbacks:** None that I can think of.

**Related GitHub Issues:** #5689 

**Related Shortcut Stories** [sc-63356]