Add `setup_inputs` to `transform` (#8732)
**Context:**

Currently, our signature and docstring for transforms comes from the
tape transform. If we don't have a tape transform, and just have a
`pass_name` definition, we don't have a place to pull the signature and
docstring from.

Also, our argument validation is lazy and only performed when actually
applying the transform to a tape. This delays potentially useful error
messages.

**Description of the Change:**

Adds an optional `setup_inputs` argument to transforms. This
`setup_inputs` function is called before any type of dispatch, including
onto a qnode, quantum function, or anything else. This allows us to
standardize and validate any inputs. We can also sort arguments into
being positional or keyword, which will be important for capturing and
lowering the transform.

**Benefits:**

Improved argument validation, preprocessing, docstrings, and signature.

**Possible Drawbacks:**

`transform` is getting very cluttered with components.

**Related GitHub Issues:**

**Example:**

For current transforms, we can apply them to a qnode with incorrect
arguments with no problem:
```
@partial(qml.transforms.merge_rotations, rtol=1e-5)
@qml.qnode(qml.device('default.qubit'))
def c():
    qml.RX(0.5, 0)
    qml.RX(0.5, 0)
    return qml.expval(qml.Z(0))
```

Errors will only be raised when the qnode is actually executed.


We can create new version of it with a `setup_inputs`:
```
def setup_inputs(atol=1e-8, include_gates=None):
    """A pass that does some stuff"""
    return (), {"atol":atol, "include_gates": include_gates}

merge_rotations = qml.transform(setup_inputs=setup_inputs, pass_name="merge-rotations")
```

And now we get an error when it is applied to a `QNode`:
```
@partial(merge_rotations, rtol=1e-5)
@qml.qnode(qml.device('default.qubit'))
def c():
    qml.RX(0.5, 0)
    qml.RX(0.5, 0)
    return qml.expval(qml.Z(0))
```
```
TypeError: setup_inputs() got an unexpected keyword argument 'rtol'
```

[sc-107939]

---------

Co-authored-by: Yushao Chen (Jerry) <chenys13@outlook.com>