Update how submodules are import top-level (#7959)
Going to class/function definitions using language servers such as
Pylance on VSCode does not work well in PennyLane because of the style
we use for importing submodules. This PR changes the import style from
`import pennylane.potato` to `from pennylane import potato`. This makes
`potato` discoverable to language servers, drastically improving
developer experience with PennyLane.

**Breaking change:**
`qml.pennylane` is no longer accessible. On `master`:
```pycon
>>> import pennylane as qml
>>> qml.pennylane
<module 'pennylane' from '/Users/mudit.pandey/repos/pennylane/pennylane/__init__.py'>
```

On this branch:
```pycon
>>> import pennylane as qml
>>> qml.pennylane
AttributeError: module 'pennylane' has no attribute 'pennylane'
```

There are many PL submodules that are missing from the top-level init
file, listed below. They may or may not be added to the `__init__` file.

- [ ] qml.bose
- [ ] qml.concurrency
- [ ] qml.debugging
- [ ] qml.devices
- [ ] qml.drawer
- [ ] qml.fermi
- [ ] qml.io
- [ ] qml.measurements
- [ ] qml.ops
- [ ] qml.optimize
- [ ] qml.pytrees
- [ ] qml.qcut
- [ ] qml.shadows
- [ ] qml.tape
- [ ] qml.transforms
- [ ] qml.workflow
- [ ] qml.queuing
- [ ] qml.typing
- [ ] qml.wires

[sc-96255]