[Capture] Add support for control flow using `autograph` (#6837)
**Context:**

Support for `autograph` in our native program capture pipeline was
introduced last release (v0.40). This release, we wish to utilize this
feature to add support for control flow when integrated with the
`QNode`.

**Description of the Change:**

Source Code 

Apply `run_autograph` to the `QNode.func` if `autograph` is requested
(default to `True`). Tests were added to ensure proper functionality
with Python native control flow (if/else, for, while) as well as with
our Pennylane native control flow (`cond`, `while_loop`, `for_loop`).

Test Suite

- Added tests for new feature under `test_capture_qnode.py` in the
`TestQNodeAutographIntegration` class.
- Specifically set the `autograph` kwarg to `False` in
`tests/capture/autograph` since the point of those tests are to test the
autograph functions themselves, and `QNode` should not be interfering.

**Benefits:**

We can now do things like (note `autograph` defaults `True`, just
setting it to be explicit),

```python
qml.capture.enable()

dev = qml.device("default.qubit", wires=[0, 1, 2])

@qml.qnode(dev, autograph=True)
def for_loop_circuit(n):
    for i in range(n):
        qml.H(i)
    return qml.state()

@qml.qnode(dev, autograph=True)
def while_loop_circuit(n):
    i = 0
    while i < n:
        qml.H(i)
        i += 1
    return qml.state()

@qml.qnode(dev, autograph=True)
def conditional_circuit(x):
    if x > 1:
        qml.H(0)
    else:
        qml.I(0)
    return qml.state()

>>> print(for_loop_circuit(2))
[0.35355335+0.j 0.35355335+0.j 0.35355335+0.j 0.35355335+0.j
 0.35355335+0.j 0.35355335+0.j 0.35355335+0.j 0.35355335+0.j]

>>> print(while_loop_circuit(2))
[0.35355335+0.j 0.35355335+0.j 0.35355335+0.j 0.35355335+0.j
 0.35355335+0.j 0.35355335+0.j 0.35355335+0.j 0.35355335+0.j]

>>> print(conditional_circuit(2))
[0.70710677+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.70710677+0.j 0.        +0.j 0.        +0.j 0.        +0.j]
```

However, if you use `autograph=False` with these circuits, you will get,
```
CaptureError: Autograph must be used when Python control flow is dependent on a dynamic variable (a function input). Please ensure autograph=True or use native control flow functions like for_loop, while_loop, etc.
```


**Possible Drawbacks:**

Uncovered two bugs:

1. If you use `qml.while_loop` with a `lambda` condition function,
`autograph` will error out. Story was created to track it @ sc-82837.
2. Cannot autograph twice in a twice. Story was created to track it @
sc-83366.

[sc-82285]

---------

Co-authored-by: Isaac De Vlugt <34751083+isaacdevlugt@users.noreply.github.com>