Add `NotImplementedError`s for `grad` and `jacobian` in `CollectOpsandMeas` (#7041)
**Context:**

Previously, if someone tries to use `CollectOpsandMeas` on workflows
involving `grad` and `jacobian`, an ambiguous error would arise.
```python
qml.capture.enable()

dev = qml.device("default.qubit", wires=2)

import jax
from pennylane.tape.plxpr_conversion import CollectOpsandMeas

@qml.qnode(dev)
def circuit(a, b):
    qml.Hadamard(0)
    qml.Hadamard(0)
    return qml.expval(qml.Z(0))

grad_fn = qml.grad(circuit)
args = (0.0, 1.0)
jaxpr = jax.make_jaxpr(grad_fn)(*args)

# Inspect for testing purposes?
>>> collector = CollectOpsandMeas()
>>> collector.eval(jaxpr.jaxpr, jaxpr.consts, *args)
ValueError: zip() argument 2 is shorter than argument 1
```

**Description of the Change:**

- Added `NotImplementedError` for both higher order primitives.
- Renamed `test_plxpr_to_tape.py` since it was also testing
`CollectOpsandMeas`

Now we get,
```python
>>> collector.eval(jaxpr.jaxpr, jaxpr.consts, *args)
NotImplementedError: CollectOpsandMeas cannot handle the grad primitive
```

**Benefits:** Improved UX.

**Possible Drawbacks:** None.

[sc-85646]