`Operator2` subclasses can override `__abstract_init__` (#9744)
**Context:**

This was mildly annoying:

```python
class CustomOp(Operator2):

    dynamic_argnames = ('theta',)

    wire_argnames = ('wires', 'work_wires')

    arg_specs = {'theta': Float, 'wires': Wire[1], 'work_wires': Wire[-1]}

    def __init__(self, theta, wires, work_wires=None):
        if work_wires is None:
            work_wires = Wires([])
        return super().__init__(self, theta, wires, work_wires)
```
```pycon
>>> CustomOp(Float, Wire[1])
TypeError: Must specify a set of wires. None is not a valid wire label.
```

We see that when we create an abstract operator, any handling of default
parameters in the subclass `__init__` is bypassed.

**Description of the Change:**

Adds a `__abstract_init__` that a subclass of `Operator2` can
*optionally* override so that it is able to fill the default values of
parameters with abstract data.

**Benefits:**

Makes creating abstract versions of operators with default arguments
easier.

**Possible Drawbacks:**

**Related GitHub Issues:**
[sc-123543]

---------

Co-authored-by: Marcus Edwards <marcusstephenedwards@gmail.com>
Co-authored-by: Marcus Edwards <94946848+comp-phys-marc@users.noreply.github.com>
Co-authored-by: Mudit Pandey <18223836+mudit2812@users.noreply.github.com>
Co-authored-by: Yushao Chen (Jerry) <chenys13@outlook.com>
Co-authored-by: David Wierichs <david.wierichs@xanadu.ai>
Co-authored-by: ringo-but-quantum <github-ringo-but-quantum@xanadu.ai>