feat: validate `Operator2` instances with static/comp args during construction (#9926)
**Context:**

If we have an `Operator2` instance that declares static / compilable
args, we would ideally like to know as early as possible if we're
feeding dynamic data into those arguments. Here's an example,
```python
import pennylane as qp
@qp.qjit(capture=True, target="mlir")
@qp.qnode(qp.device('lightning.qubit', wires=2))
def circuit(static_arg):
    qp.StaticOp(static_arg, wires=[0,1])
    return qp.expval(qp.Z(0))

ValueError: Argument 'static_arg' of operator 'StaticOp' must be a concrete, compile-time constant. A dynamic variable was provided instead. Please ensure the argument doesn't depend on function inputs.
```

**Description of the Change:**

Updates the meta class to add this validation check on construction.

**Benefits:**

Code is easier to work with and debug.

**Possible Drawbacks:** Additional logic upon construction.

[sc-126115]