Fix `InterfaceEnum` object (#6877)
**Context:**

`QNode.interface` returns a `str` type,
```python
    @property
    def interface(self) -> str:
        """The interface used by the QNode"""
        return self._interface.value
```
Therefore, this equality will never be true,
```python
from pennylane.math.interface_utils import Interface

>>> "jax" == Interface.JAX
False
```

Moreover, `str` cannot be compared with `Enum` objects at all. 🤯 

**Description of the Change:**

- Adjust the `InterfaceEnum` class to have dunder methods to overwrite
comparisons. This way it will error out if you try to compare it with a
string.
- Add test coverage for the private helpers in `qnode.py`

Now we have,
```python
from pennylane.math.interface_utils import Interface

>>> "jax" == Interface.JAX
TypeError: Cannot compare Interface with str
```

**Benefits:** Logic is correct.

**Possible Drawbacks:** None identified.

[sc-83034]

---------

Co-authored-by: Yushao Chen (Jerry) <chenys13@outlook.com>